// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQwm4JIRbGsAg22lDJlZV8SrPGtneDmwg',
    appId: '1:507058821519:web:25378118b0e21116d8d3fa',
    messagingSenderId: '507058821519',
    projectId: 'kashf-lite',
    authDomain: 'kashf-lite.firebaseapp.com',
    storageBucket: 'kashf-lite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8xAdbH-h-FmqC0EvVL3cx90_j3OW82uY',
    appId: '1:507058821519:android:1b4c1a1e7a0998acd8d3fa',
    messagingSenderId: '507058821519',
    projectId: 'kashf-lite',
    storageBucket: 'kashf-lite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaJZIAjgQP9RNoyFsJqFB31LF2t4pepcg',
    appId: '1:507058821519:ios:a45069efda6ba01ad8d3fa',
    messagingSenderId: '507058821519',
    projectId: 'kashf-lite',
    storageBucket: 'kashf-lite.firebasestorage.app',
    iosBundleId: 'com.aidata.kashfLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaJZIAjgQP9RNoyFsJqFB31LF2t4pepcg',
    appId: '1:507058821519:ios:79c2b39e967fe588d8d3fa',
    messagingSenderId: '507058821519',
    projectId: 'kashf-lite',
    storageBucket: 'kashf-lite.firebasestorage.app',
    iosBundleId: 'com.example.kashfLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQwm4JIRbGsAg22lDJlZV8SrPGtneDmwg',
    appId: '1:507058821519:web:ccd2053f88883e53d8d3fa',
    messagingSenderId: '507058821519',
    projectId: 'kashf-lite',
    authDomain: 'kashf-lite.firebaseapp.com',
    storageBucket: 'kashf-lite.firebasestorage.app',
  );
}
